function fetAddIn(){
document.writeln("<div class=\"Midtit\">");
document.writeln("  <div class=\"tit\">未来期待大作</div>");
document.writeln("  <div class=\"more\"></div>");
document.writeln("</div>");
document.writeln("<ul class=\"Mid1R_DZQS ratingGroupLike\">");
document.writeln("  <li data-generalid=\"749890\" data-type=\"5\">");
document.writeln("  <div class=\"img\">");
document.writeln("  <a target=\"_blank\" href=\"http://www.gamersky.com/z/battlefield1/\">");
document.writeln("  <img src=\"http://imgs.gamersky.com/pic/2016/20160913_zw_104_1.jpg\" width=\"70\" height=\"40\">");
document.writeln("  <div class=\"mask\"></div>");
document.writeln("  <div class=\"huo\">0</div>");
document.writeln("  </a>");
document.writeln("  </div>");
document.writeln("  <div class=\"con\">");
document.writeln("  <div class=\"t2\"><a target=\"_blank\" href=\"http://www.gamersky.com/z/battlefield1/\">战地1</a></div>");
document.writeln("  <div class=\"t3\">上市：10-21</div>");
document.writeln("  <div class=\"tag\"><a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817172.shtml\">单人模式预告</a>·<a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817065.shtml\">女玩家趣闻</a></div>");
document.writeln("  </div>");
document.writeln("  </li>");

document.writeln("  <li data-generalid=\"751527\" data-type=\"5\">");
document.writeln("  <div class=\"img\">");
document.writeln("  <a target=\"_blank\" href=\"http://www.gamersky.com/z/civilization6/\">");
document.writeln("  <img src=\"http://imgs.gamersky.com/pic/2016/20160928_zy_134_5.jpg\" width=\"70\" height=\"40\">");
document.writeln("  <div class=\"mask\"></div>");
document.writeln("  <div class=\"huo\">0</div>");
document.writeln("  </a>");
document.writeln("  </div>");
document.writeln("  <div class=\"con\">");
document.writeln("  <div class=\"t2\"><a target=\"_blank\" href=\"http://www.gamersky.com/z/civilization6/\">文明6</a></div>");
document.writeln("  <div class=\"t3\">上市：10-21</div>");
document.writeln("  <div class=\"tag\"><a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817269.shtml\">游民星空专访</a>·<a target=\"_blank\" href=\"http://www.gamersky.com/handbook/201610/816637.shtml\">建筑单位百科</a></div>");
document.writeln("  </div>");
document.writeln("  </li>");

document.writeln("  <li data-generalid=\"657998\" data-type=\"5\">");
document.writeln("  <div class=\"img\">");
document.writeln("  <a target=\"_blank\" href=\"http://www.gamersky.com/z/dragonballx2/\">");
document.writeln("  <img src=\"http://imgs.gamersky.com/pic/2016/20160823_zw_104_1.jpg\" width=\"70\" height=\"40\">");
document.writeln("  <div class=\"mask\"></div>");
document.writeln("  <div class=\"huo\">0</div>");
document.writeln("  </a>");
document.writeln("  </div>");
document.writeln("  <div class=\"con\">");
document.writeln("  <div class=\"t2\"><a target=\"_blank\" href=\"http://www.gamersky.com/z/dragonballx2/\">龙珠：超宇宙2</a></div>");
document.writeln("  <div class=\"t3\">上市：10-28</div>");
document.writeln("  <div class=\"tag\"><a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817544.shtml\">全球公开测试</a>·<a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817048.shtml\">专家模式演示</a></div>");
document.writeln("  </div>");
document.writeln("  </li>");

document.writeln("  <li data-generalid=\"341193\" data-type=\"5\">");
document.writeln("  <div class=\"img\">");
document.writeln("  <a target=\"_blank\" href=\"http://www.gamersky.com/z/dishonored2/\">");
document.writeln("  <img src=\"http://imgs.gamersky.com/pic/2016/20160607_zw_104_1.jpg\" width=\"70\" height=\"40\">");
document.writeln("  <div class=\"mask\"></div>");
document.writeln("  <div class=\"huo\">0</div>");
document.writeln("  </a>");
document.writeln("  </div>");
document.writeln("  <div class=\"con\">");
document.writeln("  <div class=\"t2\"><a target=\"_blank\" href=\"http://www.gamersky.com/z/dishonored2/\">羞辱2</a></div>");
document.writeln("  <div class=\"t3\">上市：11-11</div>");
document.writeln("  <div class=\"tag\"><a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817324.shtml\">超长游戏演示</a>·<a target=\"_blank\" href=\"http://www.gamersky.com/news/201609/815188.shtml\">女王花样虐杀</a></div>");
document.writeln("  </div>");
document.writeln("  </li>");
document.writeln("  <li data-generalid=\"549282\" data-type=\"5\">");
document.writeln("  <div class=\"img\">");
document.writeln("  <a target=\"_blank\" href=\"http://www.gamersky.com/z/watchdogs2/\">");
document.writeln("  <img src=\"http://imgs.gamersky.com/pic/2016/20160927_zy_134_1.jpg\" width=\"70\" height=\"40\">");
document.writeln("  <div class=\"mask\"></div>");
document.writeln("  <div class=\"huo\">0</div>");
document.writeln("  </a>");
document.writeln("  </div>");
document.writeln("  <div class=\"con\">");
document.writeln("  <div class=\"t2\"><a target=\"_blank\" href=\"http://www.gamersky.com/z/watchdogs2/\">看门狗2</a></div>");
document.writeln("  <div class=\"t3\">上市：11-15</div>");
document.writeln("  <div class=\"tag\"><a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817273.shtml\">任务演示视频</a>·<a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/816854.shtml\">最新实机演示</a></div>");
document.writeln("  </div>");
document.writeln("  </li>");
document.writeln("  <li data-generalid=\"314023\" data-type=\"5\">");
document.writeln("  <div class=\"img\">");
document.writeln("  <a target=\"_blank\" href=\"http://www.gamersky.com/z/ff15/\">");
document.writeln("  <img src=\"http://imgs.gamersky.com/pic/2016/20160517_zw_104_1.jpg\" width=\"70\" height=\"40\">");
document.writeln("  <div class=\"mask\"></div>");
document.writeln("  <div class=\"huo\">0</div>");
document.writeln("  </a>");
document.writeln("  </div>");
document.writeln("  <div class=\"con\">");
document.writeln("  <div class=\"t2\"><a target=\"_blank\" href=\"http://www.gamersky.com/z/ff15/\">最终幻想15</a></div>");
document.writeln("  <div class=\"t3\">上市：11-29</div>");
document.writeln("  <div class=\"tag\"><a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817539.shtml\">超长演示视频</a>·<a target=\"_blank\" href=\"http://www.gamersky.com/news/201610/817796.shtml\">引擎演示视频</a></div>");
document.writeln("  </div>");
document.writeln("  </li>");
document.writeln("</ul>");
}
var adLeg = $('#qtzads').length;
if(adLeg == 0){
	fetAddIn();
}